<div class="container">
	<div class="row">
		<div class="col">
			<div style=" background-color:lightblue; text-align: center;" class="jumbotron jumbotron-fluid">
			<div class="container">
				<h1 class="display-4">Seja muito Bem Vindo!</h1>
				<p class="lead">Este é um blog para você ficar por dentro das novidades em games</p>
			</div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col">
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="carousel-item active">
				<img src="./public/img/uma.jpeg" class="d-block w-100" alt="...">
				</div>
				<div class="carousel-item">
				<img src="./public/img/duas.jpg" class="d-block w-100" alt="...">
				</div>
				<div class="carousel-item">
				<img src="./public/img/tres.jpg" class="d-block w-100" alt="...">
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
			</div>
		</div>
	</div>
</div>

<?php 

	if (isset($posts)) {
		foreach ($posts as $key) {
		?>	
		
		<div class="container">
			<div class="row">
				<div class="col-md">
					<div class="card mb-3" style="max-width:700px;">
						<div class="row no-gutters">
							<div class="col-md-4">
								<?php   echo $this->tag->image(["public/img/" . $key->image, "class" => "card-img-top"]) ?>    </div>
								<div class="col-md-6">
									<div class="card-body">
										<h5 class="card-title"><?php echo $key->titulo ?></h5>
										<p class="card-text"><?php echo $key->post ?></p>
										<!--<a class='btn btn-primary' href='posts/excluir/<?php echo $key->id ?>'>excluir</a>-->
									<p class="card-text"><small class="text-muted">Copyright © 2019 Aisl1n - Todos os direitos reservados Política de Privacidade </small></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


		<?php	
		}
		
	}
	?>


	<div class="container-lg">
	<div class="row">
		<div class="col">
		<footer class="footer navbar-fixed-bottom">
			<div style="  padding-bottom:7em; margin-bottom:0px; background-color:lightblue; text-align: center;" class="jumbotron">
			<div class="container">
				<p class="lead">    Copyright © 2019 aisl1n games - Todos os direitos reservados
    Política de Privacidade</p>
				<p class="lead">Facebook</p>
				<p class="lead">Twitter</p>
				<p class="lead">Whatsapp</p>
				<p class="lead">Instagram</p>

			</div>
			</div>
			</footer>
		</div>
	</div>
</div>

	




