<div class="container" style="max-width: 500px; margin-top: 100px;">
	<h2>Login</h2>
	<p><?php echo $this->flashSession->output()?></p>
	<form method="post" action="login/submit">
		<div class="form-group">
			<label for="exampleInputEmail1">Email</label>
			<input type="text" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Seu Email">
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Senha</label>
			<input type="password" type="text"  class="form-control" name="senha" id="exampleInputPassword1" placeholder="Sua Senha">
		</div>
		<button type="submit" class="btn btn-primary">login</button>
	</form>	
</div>


