


<p><?php echo $this->flashSession->output() ?></p>
<div class="container" style="max-width: 500px; margin-top: 100px;">
	<h2>Cadastre-se</h2>
	<form method="post" action="cadastro/submit">
		<div class="form-group">
			<label for="exampleInputEmail1">Nome</label>
			<input type="text" class="form-control" id="exampleInputEmail1" name="nome" aria-describedby="emailHelp" placeholder="Insira seu Nome">
		</div>
		<div class="form-group">
			<label for="exampleInputEmail1">Email</label>
			<input type="text" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Insira seu email">
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Senha</label>
			<input type="password" class="form-control" name="senha" id="exampleInputPassword1" placeholder="Insira sua Senha">
		</div>
		<button type="submit" class="btn btn-primary">Cadastrar</button>
	</form>	
</div>