<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
       <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
        <a class="navbar-brand" href="inicio">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
	    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li>
                <a class="nav-link" href="login/logout">Logout</a>
            </li>
    	</div>
	</nav>
	
	</body>
</html>

<p><?php echo $this->flashSession->output() ?></p>
<div class="container" style="max-width: 500px; margin-top: 100px;">
	<h3>Adicionar uma nova postagem</h3>

	<form method="post" action="posts/submit" enctype="multipart/form-data">
   
    <div class="form-group">
      <label for="exampleInputEmail1">Título da postagem</label>
			<input type="text" class="form-control" id="titulo" name="titulo" aria-describedby="emailHelp"></>    
    </div>
 

		<div class="form-group">
			<label for="exampleInputEmail1">No que você está pensando, <?php echo $this->session->get('nome'); ?> ?</label> 
			<textarea type="text" class="form-control" id="exampleInputEmail1" name="post" aria-describedby="emailHelp"></textarea>
		</div>


		<div class="form-group">
			<label for="exampleInputPassword1">Carregue sua imagem</label>
			<input type="file" class="form-control-file" name="image" id="exampleFormControlFile1">
		</div>
		<input type="hidden" name="id" value='<?php echo $this->session->get('id') ?>'>
		<button type="submit" class="btn btn-primary">Enviar</button>
	
  </form>	
</div>








